POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
  "username": "harsh01",
  "password": "123456",
  "email": "harsh@gmail.com",
  "name": "Harsh"
}

###
POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "email": "harsh@gmail.com",
    "password": "123456"
}
###
GET http://localhost:8000/me HTTP/1.1
Content-Type: application/json


###
PUT http://localhost:8000/profile HTTP/1.1
Content-Type: application/json

{
  "headline": "Full_stack_developer",
  "location": "ghaziabad",
  "skills": ["frontend", "backend"],
   "website": "mypotfolio",
  "bio": "Full Stack Developer focused on building scalable web applications and AI-driven tools.",
  "currentpost": "MERN Stack Developer",
  "pastwork": [
    {
      "company": "MeshUp",
      "position": "Backend Developer",
       "years": "2024"
    }
  ],
  "education": [
    {
       "school": "ingrham",
      "degree": "B.Tech",
      "fieldofstudy": "full stack dev"
     
    }
  ]
}


###
GET http://localhost:8000/users HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/harsh/feed/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/comments/6995c9723d359a33ed06655c HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/like/6995c9723d359a33ed06655c HTTP/1.1
Content-Type: application/json